In [4]:
import time
import cv2
import cv2.aruco as A
import numpy as np

dictionary = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_50)
board = cv2.aruco.CharucoBoard_create(7,7,.025,.0125,dictionary)
img = board.draw((100*7,100*7))

#Dump the calibration board to a file
cv2.imwrite('charuco.png',img)


#Start capturing images for calibration
cap = cv2.VideoCapture(0)

allCorners = []
allIds = []
decimator = 0
for i in range(300):

    ret,frame = cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    res = cv2.aruco.detectMarkers(gray,dictionary)

    if len(res[0])>0:
        res2 = cv2.aruco.interpolateCornersCharuco(res[0],res[1],gray,board)
        if res2[1] is not None and res2[2] is not None and len(res2[1])>3 and decimator%3==0:
            allCorners.append(res2[1])
            allIds.append(res2[2])

        cv2.aruco.drawDetectedMarkers(gray,res[0],res[1])

    cv2.imshow('frame',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    decimator+=1

imsize = gray.shape

#Calibration fails for lots of reasons. Release the video if we do
try:
    cal = cv2.aruco.calibrateCameraCharuco(allCorners,allIds,board,imsize,None,None)
except:
    cap.release()

cap.release()
cv2.destroyAllWindows()

In [5]:
cal

(0.18763745329260337, array([[ 722.47843533,    0.        ,  345.76148326],
        [   0.        ,  719.46836039,  215.29777186],
        [   0.        ,    0.        ,    1.        ]]), array([[ 0.060491  , -0.16982899,  0.00052914,  0.00505482,  0.31064351]]), [array([[ 2.12803922],
         [-2.29445827],
         [ 0.26830789]]),
  array([[-2.13604439],
         [ 2.29697394],
         [-0.19911358]]),
  array([[ 2.10149086],
         [-2.28621968],
         [ 0.14201833]]),
  array([[ 2.08596923],
         [-2.30199062],
         [ 0.1074693 ]]),
  array([[ 2.07382803],
         [-2.30829953],
         [ 0.0784255 ]]),
  array([[ 2.07705947],
         [-2.28991501],
         [ 0.08038616]]),
  array([[ 2.14649386],
         [-2.24437601],
         [ 0.14888418]]),
  array([[ 2.16645201],
         [-2.22139933],
         [ 0.16601675]]),
  array([[ 2.17138135],
         [-2.21415302],
         [ 0.18805187]]),
  array([[ 2.14998861],
         [-2.2187801 ],
         [ 0.16565358]]

In [6]:
retval, cameraMatrix, distCoeffs, rvecs, tvecs = cal

In [7]:
print(cameraMatrix)
print(distCoeffs)

[[ 722.47843533    0.          345.76148326]
 [   0.          719.46836039  215.29777186]
 [   0.            0.            1.        ]]
[[ 0.060491   -0.16982899  0.00052914  0.00505482  0.31064351]]
